(()=>{
const section=document.createElement('section');section.className='mission scroll-reveal';section.id='mission';section.innerHTML=`<div class="mission-copy"><p class="chapter">LIVE / MISSION CONTROL</p><h2>Путешествие начинается<br><span>задолго до взлёта.</span></h2><p>Выберите этап — SAYGAV покажет следующий важный шаг.</p><div class="scenes"><button class="active" data-s="plan">Я планирую</button><button data-s="soon">Скоро вылет</button><button data-s="airport">В аэропорту</button><button data-s="arrived">Я прибыл</button></div><article class="scene"><small id="scene-step">ЭТАП 01 / ПОДГОТОВКА</small><h3 id="scene-title">Соберите основу маршрута</h3><p id="scene-copy">Проверьте правила страны, микрочип, вакцинацию и сроки сертификатов.</p><a id="scene-link" href="#planner">Открыть Trip Builder <b>↗</b></a></article></div><div class="mission-visual"><div class="orbit a"></div><div class="orbit b"></div><div class="globe"><span>LCA</span><i>✦</i><strong>ATH</strong><small>LIVE ROUTE</small></div><aside class="ready"><span>ГОТОВНОСТЬ МАРШРУТА</span><strong data-count="72">0%</strong><div><i></i></div><small>Следующая проверка · документы</small></aside><button class="film-open"><i>▶</i><span><b>Смотреть историю</b><small>02:18 · SERVICE DOGS</small></span></button></div>`;document.querySelector('.hero').after(section);
const data={plan:['ЭТАП 01 / ПОДГОТОВКА','Соберите основу маршрута','Проверьте правила страны, микрочип, вакцинацию и сроки сертификатов.','#planner','Открыть Trip Builder'],soon:['ЭТАП 02 / ЗА 48 ЧАСОВ','Подтвердите перелёт','Получите письменное подтверждение перевозчика и соберите документы в одну папку.','#journey-os','Запустить AI-аудит'],airport:['ЭТАП 03 / ДЕНЬ ВЫЛЕТА','Держите главное под рукой','Паспорт, сертификат и подтверждение перевозчика — без поиска в багаже.','#planner','Чек-лист дня вылета'],arrived:['ЭТАП 04 / НОВЫЙ ГОРОД','Найдите спокойный маршрут','Откройте карту парков, клиник и dog-friendly мест рядом с проживанием.','https://www.google.com/maps/search/dog+friendly+parks','Открыть Google Maps']};
section.querySelector('.scenes').onclick=e=>{const b=e.target.closest('button');if(!b)return;section.querySelectorAll('.scenes button').forEach(x=>x.classList.toggle('active',x===b));const d=data[b.dataset.s],card=section.querySelector('.scene');card.classList.remove('enter');void card.offsetWidth;card.classList.add('enter');['step','title','copy'].forEach((x,i)=>section.querySelector('#scene-'+x).textContent=d[i]);const a=section.querySelector('#scene-link');a.href=d[3];a.innerHTML=d[4]+' <b>↗</b>';if(d[3][0]!=='#'){a.target='_blank';a.rel='noopener'}else a.removeAttribute('target')};
const modal=document.createElement('div');modal.className='film-modal';modal.hidden=true;modal.innerHTML=`<div class="film-bg" data-close></div><div class="film-frame"><button data-close aria-label="Закрыть">×</button><div class="player"></div><p><b>Собака на борту</b><span>Практическое видео о перелёте с собакой в салоне самолёта.</span></p></div>`;document.body.appendChild(modal);section.querySelector('.film-open b').textContent='Собака летит в самолёте';section.querySelector('.film-open').onclick=()=>{modal.hidden=false;document.body.classList.add('modal-open');modal.querySelector('.player').innerHTML='<iframe src="https://www.youtube-nocookie.com/embed/NlAfOB2kRPs?autoplay=1&rel=0" title="Перелёт с собакой в салоне самолёта" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>'};modal.onclick=e=>{if(e.target.closest('[data-close]')){modal.hidden=true;modal.querySelector('.player').innerHTML='';document.body.classList.remove('modal-open')}};
const flying=document.createElement('div');flying.className='flying-plane';flying.setAttribute('aria-hidden','true');flying.innerHTML=`<div class="contrail"></div><div class="plane-body"><b class="nose"></b><div class="dog-window">🐶</div><div class="dog-window">🐕</div><div class="dog-window">🐶</div><span>SAYGAV</span><i class="wing top"></i><i class="wing bottom"></i><em class="tail"></em></div>`;document.body.appendChild(flying);
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;e.target.classList.add('visible');const c=e.target.querySelector('[data-count]');if(c&&!c.dataset.done){c.dataset.done=1;let n=0;const tick=()=>{n+=2;c.textContent=Math.min(n,72)+'%';if(n<72)requestAnimationFrame(tick)};tick()}}),{threshold:.15});document.querySelectorAll('.mission,.manifesto,.journey,.photo-story,.resources,.planner,.closing').forEach(x=>{x.classList.add('scroll-reveal');observer.observe(x)});
const hero=document.querySelector('.hero');addEventListener('scroll',()=>{if(scrollY<innerHeight)hero.style.setProperty('--shift',scrollY*.1+'px')},{passive:true});
})();
